### ISSUE TITLE
no jwplayer found?

### ISSUE THREAD

**Issue by ghost** [TheFox/streamcloud#1]
Hi, habe heute mal dein script testen wollen, da taucht aber leider dieser fehler auf:
[2015/07/04 14:32:16+0200] download.ERROR: no jwplayer found
Wie kann ich diesen Error lösen?

mfg.

**Comment by TheFox** [comment]
Taucht dieser Fehler bei allen Links auf, oder nur bei bestimmten? Hab' es jetzt mit mehreren Links getestet, erfolgreich.

Ich empfehle die Verwendung von <https://rg3.github.io/youtube-dl/> - hat (1) mehr Module fuer diverse Seiten zur Verfuegung und (2) wird youtube-dl staendig weiter entwickelt. ;)
